version: '3'
services:
  discord-bot:
    container_name: pool-party-bot
    build: discord-bot
    volumes:
      - '.env:/usr/src/app/.env'
    #command: npm start  #commande moved to Dockerfile

  db:
      container_name: postgres
      image: postgres:12-alpine
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PW}
        - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
      ports:
        - "5432:5432"
      volumes:
        - db-data:/var/lib/postgresql/data
      restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80" #map port 80 to 5050 to avoir collision
    restart: always

volumes:
  db-data:
    driver: local